# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonPrintFileResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CommonPrintFileResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1f\x43ommonPrintFileResponsePb.proto\"\x90\x01\n\x19\x43ommonPrintFileResponsePb\x12\x10\n\x08\x46ileName\x18\x01 \x01(\t\x12\x19\n\x11\x46ileExtensionName\x18\x02 \x01(\t\x12\x13\n\x0bPrinterName\x18\x03 \x01(\t\x12\x12\n\nFileStream\x18\x04 \x01(\t\x12\x1d\n\x15PopPrinterSettingFlag\x18\x05 \x01(\x08\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
)




_COMMONPRINTFILERESPONSEPB = _descriptor.Descriptor(
  name='CommonPrintFileResponsePb',
  full_name='CommonPrintFileResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FileName', full_name='CommonPrintFileResponsePb.FileName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FileExtensionName', full_name='CommonPrintFileResponsePb.FileExtensionName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PrinterName', full_name='CommonPrintFileResponsePb.PrinterName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='FileStream', full_name='CommonPrintFileResponsePb.FileStream', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PopPrinterSettingFlag', full_name='CommonPrintFileResponsePb.PopPrinterSettingFlag', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['CommonPrintFileResponsePb'] = _COMMONPRINTFILERESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonPrintFileResponsePb = _reflection.GeneratedProtocolMessageType('CommonPrintFileResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _COMMONPRINTFILERESPONSEPB,
  '__module__' : 'CommonPrintFileResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:CommonPrintFileResponsePb)
  })
_sym_db.RegisterMessage(CommonPrintFileResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
