# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderListRequestPb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from ProtobufPy import MessageRequestPb_pb2 as MessageRequestPb__pb2, OrderRequestPb_pb2 as OrderRequestPb__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderListRequestPb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x18OrderListRequestPb.proto\x1a\x16MessageRequestPb.proto\x1a\x14OrderRequestPb.proto\"z\n\x12OrderListRequestPb\x12!\n\x08oldDatas\x18\x01 \x03(\x0b\x32\x0f.OrderRequestPb\x12\x1e\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x0f.OrderRequestPb\x12!\n\x06params\x18\x03 \x03(\x0b\x32\x11.MessageRequestPbB\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[MessageRequestPb__pb2.DESCRIPTOR,OrderRequestPb__pb2.DESCRIPTOR,])




_ORDERLISTREQUESTPB = _descriptor.Descriptor(
  name='OrderListRequestPb',
  full_name='OrderListRequestPb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oldDatas', full_name='OrderListRequestPb.oldDatas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datas', full_name='OrderListRequestPb.datas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='params', full_name='OrderListRequestPb.params', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=196,
)

_ORDERLISTREQUESTPB.fields_by_name['oldDatas'].message_type = OrderRequestPb__pb2._ORDERREQUESTPB
_ORDERLISTREQUESTPB.fields_by_name['datas'].message_type = OrderRequestPb__pb2._ORDERREQUESTPB
_ORDERLISTREQUESTPB.fields_by_name['params'].message_type = MessageRequestPb__pb2._MESSAGEREQUESTPB
DESCRIPTOR.message_types_by_name['OrderListRequestPb'] = _ORDERLISTREQUESTPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderListRequestPb = _reflection.GeneratedProtocolMessageType('OrderListRequestPb', (_message.Message,), {
  'DESCRIPTOR' : _ORDERLISTREQUESTPB,
  '__module__' : 'OrderListRequestPb_pb2'
  # @@protoc_insertion_point(class_scope:OrderListRequestPb)
  })
_sym_db.RegisterMessage(OrderListRequestPb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
