# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrderFinishResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from ProtobufPy import MessageResponsePb_pb2 as MessageResponsePb__pb2, OrderResponsePb_pb2 as OrderResponsePb__pb2, \
	CommonPrintFileResponsePb_pb2 as CommonPrintFileResponsePb__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='OrderFinishResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x1bOrderFinishResponsePb.proto\x1a\x15OrderResponsePb.proto\x1a\x17MessageResponsePb.proto\x1a\x1f\x43ommonPrintFileResponsePb.proto\"\xa6\x01\n\x15OrderFinishResponsePb\x12#\n\torderInfo\x18\x01 \x01(\x0b\x32\x10.OrderResponsePb\x12$\n\x08messages\x18\x02 \x03(\x0b\x32\x12.MessageResponsePb\x12.\n\nprintFiles\x18\x03 \x03(\x0b\x32\x1a.CommonPrintFileResponsePb\x12\x12\n\nisShooting\x18\x04 \x01(\x08\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[OrderResponsePb__pb2.DESCRIPTOR,MessageResponsePb__pb2.DESCRIPTOR,CommonPrintFileResponsePb__pb2.DESCRIPTOR,])




_ORDERFINISHRESPONSEPB = _descriptor.Descriptor(
  name='OrderFinishResponsePb',
  full_name='OrderFinishResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orderInfo', full_name='OrderFinishResponsePb.orderInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='OrderFinishResponsePb.messages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='printFiles', full_name='OrderFinishResponsePb.printFiles', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isShooting', full_name='OrderFinishResponsePb.isShooting', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=279,
)

_ORDERFINISHRESPONSEPB.fields_by_name['orderInfo'].message_type = OrderResponsePb__pb2._ORDERRESPONSEPB
_ORDERFINISHRESPONSEPB.fields_by_name['messages'].message_type = MessageResponsePb__pb2._MESSAGERESPONSEPB
_ORDERFINISHRESPONSEPB.fields_by_name['printFiles'].message_type = CommonPrintFileResponsePb__pb2._COMMONPRINTFILERESPONSEPB
DESCRIPTOR.message_types_by_name['OrderFinishResponsePb'] = _ORDERFINISHRESPONSEPB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrderFinishResponsePb = _reflection.GeneratedProtocolMessageType('OrderFinishResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _ORDERFINISHRESPONSEPB,
  '__module__' : 'OrderFinishResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:OrderFinishResponsePb)
  })
_sym_db.RegisterMessage(OrderFinishResponsePb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
