# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PageResponsePb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PageResponsePb.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\025TomTaw.eWordRIS.Proto'),
  serialized_pb=_b('\n\x14PageResponsePb.proto\x1a\x19google/protobuf/any.proto\"\x87\x01\n\x0ePageResponsePb\x12\x11\n\tisSuccess\x18\x01 \x01(\x08\x12\x12\n\nresultDesc\x18\x02 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x14.google.protobuf.Any\x12\x1b\n\x08pageBase\x18\x04 \x01(\x0b\x32\t.PageBase\x12\r\n\x05token\x18\x05 \x01(\t\"G\n\x08PageBase\x12\x13\n\x0b\x63urrentPage\x18\x01 \x01(\x05\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\x12\x14\n\x0ctotalRecords\x18\x03 \x01(\x05\x42\x18\xaa\x02\x15TomTaw.eWordRIS.Protob\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_PAGERESPONSEPB = _descriptor.Descriptor(
  name='PageResponsePb',
  full_name='PageResponsePb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='PageResponsePb.isSuccess', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resultDesc', full_name='PageResponsePb.resultDesc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='PageResponsePb.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageBase', full_name='PageResponsePb.pageBase', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='PageResponsePb.token', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=187,
)


_PAGEBASE = _descriptor.Descriptor(
  name='PageBase',
  full_name='PageBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentPage', full_name='PageBase.currentPage', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='PageBase.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalRecords', full_name='PageBase.totalRecords', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=260,
)

_PAGERESPONSEPB.fields_by_name['data'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_PAGERESPONSEPB.fields_by_name['pageBase'].message_type = _PAGEBASE
DESCRIPTOR.message_types_by_name['PageResponsePb'] = _PAGERESPONSEPB
DESCRIPTOR.message_types_by_name['PageBase'] = _PAGEBASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PageResponsePb = _reflection.GeneratedProtocolMessageType('PageResponsePb', (_message.Message,), {
  'DESCRIPTOR' : _PAGERESPONSEPB,
  '__module__' : 'PageResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:PageResponsePb)
  })
_sym_db.RegisterMessage(PageResponsePb)

PageBase = _reflection.GeneratedProtocolMessageType('PageBase', (_message.Message,), {
  'DESCRIPTOR' : _PAGEBASE,
  '__module__' : 'PageResponsePb_pb2'
  # @@protoc_insertion_point(class_scope:PageBase)
  })
_sym_db.RegisterMessage(PageBase)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
